### ISSUE TITLE
How to uninstall gphotos unlimited?

### ISSUE THREAD

**Issue by M1hao** [Kolass2004/Unlimited-GooglePhotosBackupMod#1]
How can I uninstall your module? It isn't listed on Magisk. I cannot use my Revolut app with emulation. 
Thanks for your help!

**Comment by Kolass2004** [comment]
![Screenshot_2024-09-29-15-09-33-443_com topjohnwu magisk](https://github.com/user-attachments/assets/840596a1-be97-4da4-8932-164b221a95fa)
You have a option for remove in magisk, if isn't showing , uninstall by using recovery , Remove data/adb/modules

**Comment by M1hao** [comment]
I do not have custom recovery (Pixel 8 Pro) and modul doesn't show up in Magisk. Pls help

**Comment by M1hao** [comment]
In Magisk folder on drive it isn't listed as well

**Comment by M1hao** [comment]
![Screenshot_20240929-114743](https://github.com/user-attachments/assets/3584e2e0-b54d-4189-88fc-e80e94f28738)
