### ISSUE TITLE
Cannot uninstall 

### ISSUE THREAD

**Issue by M1hao** [Kolass2004/Unlimited-GooglePhotosBackupMod#2]
I do not have custom recovery (Pixel 8 Pro) and modul doesn't show up in Magisk. Pls help
![Screenshot_20240929-114743](https://github.com/user-attachments/assets/846bc946-9ad6-4471-a805-caee9209bc23)

**Comment by M1hao** [comment]
![Screenshot_20240929-115128](https://github.com/user-attachments/assets/78c95d72-fe9b-4bf3-a663-cf20a0ce5600)

**Comment by Kolass2004** [comment]
No brother , my modules isn't installed in your device, I think that is occurring by pixelxpert, 
My modules only spoof Google photos app only, delete modules folder then again install all of your modules

**Comment by M1hao** [comment]
Ok mate, thanks a lot and sorry for bothering. I will try.

**Comment by M1hao** [comment]
PS. Audio mods caused that

**Comment by Kolass2004** [comment]
It's ok , Enjoy your day mate ✨
